version: "2"
services:
  storage-laravel-project:
    image: alpine:latest
    volumes:
      - ./setup.sh:/setup.sh
      - ./../public:/var/www
    command: /bin/true

  laravel-project-database-data:
    image: alpine:latest
    volumes:
      - ./../db/laravel_automation_dump.sql:/tmp/laravel_automation_dump.sql
      - ./../docker/database-import.sh:/tmp/database-import.sh
      - ./../db/data:/var/lib/mysql
    command: /bin/true

  laravel-project-db:
    image: mysql:5.7
    container_name: laravel-project.db
    volumes_from:
      - laravel-project-database-data
    links:
      - laravel-project-database-data
    environment:
      MYSQL_USER: "laraveluser"
      MYSQL_PASSWORD: "test1234!"
      MYSQL_DATABASE: "laraveldb"
      MYSQL_ROOT_PASSWORD: ""

  automation-laravel:
   image: poupou/alpine-nginx-php7fpm:latest
   container_name: laravel-project.dev
   volumes_from:
     - storage-laravel-project
   links:
      - laravel-project-db
version: "2"
services:
  storage-laravel-project:
    image: alpine:latest
    volumes:
      - ./setup.sh:/setup.sh
      - ./../public:/var/www
    command: /bin/true

  laravel-project-database-data:
    image: alpine:latest
    volumes:
      - ./../db/laravel_automation_dump.sql:/tmp/laravel_automation_dump.sql
      - ./../docker/database-import.sh:/tmp/database-import.sh
      - ./../db/data:/var/lib/mysql
    command: /bin/true

  laravel-project-db:
    image: mysql:5.7
    container_name: laravel-project.db
    volumes_from:
      - laravel-project-database-data
    links:
      - laravel-project-database-data
    environment:
      MYSQL_USER: "laraveluser"
      MYSQL_PASSWORD: "test1234!"
      MYSQL_DATABASE: "laraveldb"
      MYSQL_ROOT_PASSWORD: ""

  automation-laravel:
   image: poupou/alpine-nginx-php7fpm:latest
   container_name: laravel-project.dev
   volumes_from:
     - storage-laravel-project
   links:
      - laravel-project-db
